# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md

pr: none

pool: VSEngSS-MicroBuild2022-1ES

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      policheck:
        enabled: true
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true

    stages:
      - stage: Build
        jobs:
          - job: Build
            templateContext:
              mb:
                signing:
                  enabled: true
                  signType: $(SignType)
                  zipSources: false
            steps:
              - template: /build/build.yml@self
                parameters:
                    BuildConfiguration: $(BuildConfiguration)
                    BuildPlatform: $(BuildPlatform)
                    Sign: true
                    PublishArtifactTemplate: /build/templates/1es-publish-task.yml@self

              - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
                displayName: Clean up
                condition: succeededOrFailed()
