# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

trigger: none

pr:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md

pool:
  vmImage: windows-2022

steps:
- template: /build/build.yml@self
  parameters:
      BuildConfiguration: $(BuildConfiguration)
      BuildPlatform: $(BuildPlatform)
      Docker: true
      PublishArtifactTemplate: /build/templates/ado-publish-task.yml@self
